name: GitHub Action 2 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: | 
          docker build -t xxfuronix/ue19_labo09-10:main .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'xxfuronix/ue19_labo09-10:main'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
